export const SHARED_LOCALIZATIONS = {
  "English": {
    "play": "Play",
    "start": "Start",
    "next": "Next",
    "submit": "Submit",
    "try_again": "Try Again",
    "back": "Back",
    "play_again": "Play Again",
    "listen": "Listen",
    "repeat": "Repeat",
    "return_dashboard": "Return to Dashboard",
    "time_left": "Time Left",
    "score": "Score",
    "hints": "Hints Used",
    "level": "Level",
    "support_active": "Support Active (Easier Version)",
    "watch_carefully": "Watch the flashing sequence carefully!",
    "repeat_pattern": "Repeat the pattern shown...",
    "great_job": "Great job!",
    "game_over": "Game Over",
    "clicks": "Clicks",
    "progress": "Progress",
    "replay_flash": "Replay Flash",
    "cancel": "Cancel",
    "exit": "Exit",
    "object_to_find": "Find the object:",
    "correct_match": "Correct Match!",
    "wrong_match": "Try again!",
    "find_different": "Find the odd one out",
    "read_story": "Read Story",
    "keep_going": "Keep going",
    "wrong_seq": "Oops! Wrong sequence. Let's repeat.",
    "next_item_hint": "Hint: The next item is",
    "go_to_questions": "Go to Questions",
    "question": "Question",
    "submit_answer": "Submit Answer",
    "shuffle": "Shuffle",
    "generating": "Generating...",
    "playing": "Playing... Click to Stop",
    "error": "Error"
  },
  "Assamese": {
    "play": "খেলক",
    "start": "আৰম্ভ কৰক",
    "next": "পৰৱৰ্তী",
    "submit": "জমা কৰক",
    "try_again": "পুনৰ চেষ্টা কৰক",
    "back": "পাছলৈ",
    "play_again": "পুনৰ খেলক",
    "listen": "শুনক",
    "repeat": "পুনৰাবৃত্তি কৰক",
    "return_dashboard": "মুখ্য পৃষ্ঠালৈ যাওক",
    "time_left": "অৱশিষ্ট সময়",
    "score": "স্কোৰ",
    "hints": "ব্যৱহৃত সংকেত",
    "level": "স্তৰ",
    "support_active": "সহায় সক্ৰিয় (সহজ সংস্কৰণ)",
    "watch_carefully": "জিলিকি উঠা ক্ৰমটো ভালদৰে চাওক!",
    "repeat_pattern": "দেখুওৱা ক্ৰমটো কৰক...",
    "great_job": "অতি সুন্দৰ!",
    "game_over": "খেল সমাপ্ত",
    "clicks": "ক্লিক",
    "progress": "অগ্ৰগতি",
    "replay_flash": "ক্ৰমটো আকৌ দেখুওৱাওক",
    "cancel": "বাতিল কৰক",
    "exit": "প্ৰস্থান কৰক",
    "object_to_find": "বস্তুটো বিচাৰক:",
    "correct_match": "শুদ্ধ হৈছে!",
    "wrong_match": "আকৌ চেষ্টা কৰক!",
    "find_different": "আটাইতকৈ বেলেগ ছবিটো বাছক",
    "read_story": "সাধুটো পঢ়ক",
    "keep_going": "কৰি যাওক",
    "wrong_seq": "ওহ! ভুল ক্ৰম। আকৌ চাওক।",
    "next_item_hint": "সংকেত: পৰৱৰ্তী ছবিখন হৈছে",
    "go_to_questions": "প্ৰশ্নলৈ যাওক",
    "question": "প্ৰশ্ন",
    "submit_answer": "উত্তৰ জমা কৰক",
    "shuffle": "আউল-জাউল কৰক",
    "generating": "কণ্ঠ প্ৰস্তুত কৰা হৈছে...",
    "playing": "বাজি আছে... বন্ধ কৰক",
    "error": "ত্ৰুটি"
  },
  "Bengali": {
    "play": "খেলুন",
    "start": "শুরু করুন",
    "next": "পরবর্তী",
    "submit": "জমা দিন",
    "try_again": "আবার চেষ্টা করুন",
    "back": "পেছনে",
    "play_again": "আবার খেলুন",
    "listen": "শুনুন",
    "repeat": "পুনরায় শুনুন",
    "return_dashboard": "ড্যাশবোর্ডে ফিরে যান",
    "time_left": "অবশিষ্ট সময়",
    "score": "স্কোর",
    "hints": "ব্যবহৃত সূত্র",
    "level": "স্তর",
    "support_active": "সহয়তা সক্রিয় (সহজ সংস্করণ)",
    "watch_carefully": "ছবিগুলির ক্রমটি মনোযোগ দিয়ে দেখুন!",
    "repeat_pattern": "দেখানো ক্রমটি জোড়া দিন...",
    "great_job": "দারুণ হয়েছে!",
    "game_over": "খেলা শেষ",
    "clicks": "ক্লিক",
    "progress": "অগ্রগতি",
    "replay_flash": "ক্রমটি আবার দেখান",
    "cancel": "বাতিল করুন",
    "exit": "প্রস্থান করুন",
    "object_to_find": "বস্তুটি খুঁজুন:",
    "correct_match": "সভিক উত্তর!",
    "wrong_match": "আবার চেষ্টা করুন!",
    "find_different": "অন্যরকম ছবিটি খুঁজুন",
    "read_story": "গল্পটি পড়ুন",
    "keep_going": "চালিয়ে যান",
    "wrong_seq": "ভুল ক্রম। আবার দেখুন।",
    "next_item_hint": "সূত্র: পরের ছবিটি হলো",
    "go_to_questions": "প্রশ্নে যান",
    "question": "প্রশ্ন",
    "submit_answer": "উত্তর জমা দিন",
    "shuffle": "ওলটপালট করুন",
    "generating": "কণ্ঠস্বর তৈরি হচ্ছে...",
    "playing": "বাজছে... বন্ধ করুন",
    "error": "ভুল"
  },
  "Meitei": {
    "play": "ꯁꯥꯟꯅꯕꯤꯌꯨ",
    "start": "ꯍꯧꯕꯤꯌꯨ",
    "next": "ꯃꯊꯪ",
    "submit": "ꯁꯕꯃꯤꯠ",
    "try_again": "ꯑꯃꯨꯛꯇꪪ ꯍꯣꯠꯅꯕꯤꯌꯨ",
    "back": "ꯍꯟꯗꯨꯅꯥ",
    "play_again": "ꯑꯃꯨꯛꯇꪪ ꯁꯥꯟꯅꯕꯤꯌꯨ",
    "listen": "ꯇꯥꯕꯤꯌꯨ",
    "repeat": "ꯑꯃꯨꪛ ꯍꯥꯏꯕꯤꯌꯨ",
    "return_dashboard": "ꯗꯦꯁꯕꯣꯔꯗꯇꯥ ꯍꯟꯂꯨ",
    "time_left": "ꯃꯇꝝ ꯂꯦꯝꯍꯧꯔꯤꯕꪥ",
    "score": "ꯁ꯭ꯀꯣৰ",
    "hints": "ꯍꯤꯟꯠ ꯁꯤꯖꯤꯟꯅꯈꯤꯕꪥ",
    "level": "ꯊꯥꯛ",
    "support_active": "ꯃꯇꯦꯡ ꯂꯧꯕꯤ (ꯑꯔꯥꯏꯕꪥ)",
    "watch_carefully": "ꯁꯦꯛꯌꯨꯑꯦꯟꯁ ꯐ꯭ꯂꯦꯁ ꯇꯧꯔꯀꯄꯥ ꯃꯇꯨꯡ ꯌেইংꯕꯤꯌꯨ!",
    "repeat_pattern": "ꯁꯦꯛꯌꯨꯑꯦꯟꯁ ꯑꯗꯨ ꯍꯟꯕꯤꯌꯨ...",
    "great_job": "ꯌꯥꯝ ꯐꯖꯅꯥ!",
    "game_over": "ꯒꯦꯝ ꯂꯣꯏৰꯦ",
    "clicks": "ꯀ꯭ꯂꯤꯛ ꯇꯧꯔꯀꯄꪥ",
    "progress": "ꯃꯥꯡꪗ",
    "replay_flash": "ꯐ꯭ꯂꯦꯁ ꯑꯃꯨꯛ ꯌেইংꯕꯤꯌꪥ",
    "cancel": "ꯀꯦꯟꯁꯦꯜ",
    "exit": "ꯊꯣꯛꯂꯣ",
    "object_to_find": "ꯄꯣꯠꯁꯛ ꯐꯪꯕꯤꯌꯨ:",
    "correct_match": "ꯑꯆꯨꯝꯕꯅꯤ!",
    "wrong_match": "ꯑꯃꯨꪛ ꯍꯣꯠꯅꯕꯤꯌꯨ!",
    "find_different": "ꯈꯦꯠꯅꯕꯥ ꯄꯣꯠꯁꯛ ꯈꯟꯕꯤꯌꯨ",
    "read_story": "ꯋꯥꯔꯤ ꯇꯥꯕꯤꯌꯨ",
    "keep_going": "ꯃꯈꯥ ꯆꯠꯊꯕꯤꯌꯨ",
    "wrong_seq": "ꯑꯔꯥꯟꯕꪥ ꯁꯦꯛꯌꯨꯑꯦꯟꯁ꯫ ꯑꯃꯨꯛ ꯌেইংꯕꯤꯌꯨ꯫",
    "next_item_hint": "ꯍꯤꯟꯠ: ꯃꯊꯪꯒꯤ ꯄꯣꯠꯁꯛ ꯑꯨꯗꯤ",
    "go_to_questions": "ꯋꯥꯍꯡꯗꯥ ꯆꯠꯂꯨ",
    "question": "ꯋꯥꯍꯡ",
    "submit_answer": "ꯋꯥꯍꯡ ꯁꯕꯃꯤꯠ",
    "shuffle": "ꯍꯣꯡꯗꯣꯛ-ꯍꯣꯡꯖꯤꯟ",
    "generating": "ꯈꯣꯟꯖꯦꯜ ꯁꯦꯝꯕꯤꯔꯤ...",
    "playing": "ꯂꯥꯎꯔꯤ... ꯂꯣꯏꯔꯦ",
    "error": "ꯑꯔꯥꯟꯕꪥ"
  },
  "Mizo": {
    "play": "Kah rawh",
    "start": "Tan rawh",
    "next": "A dawt",
    "submit": "Submit",
    "try_again": "Chhin chhiah leh",
    "back": "Kir leh",
    "play_again": "Khel leh rawh",
    "listen": "Ngaithla rawh",
    "repeat": "Sawi nawn leh",
    "return_dashboard": "Dashboard ah kir leh",
    "time_left": "Hun la awm",
    "score": "Score",
    "hints": "Hint Hman zat",
    "level": "Level",
    "support_active": "Taimakna (A awlsam zawk)",
    "watch_carefully": "A rawn eng in dawt kha en fimkhur rawh!",
    "repeat_pattern": "A in dawt dan ang khan hmet rawh...",
    "great_job": "I ti tha lutuk!",
    "game_over": "Game zo",
    "clicks": "Hmehtu",
    "progress": "Hmasawnna",
    "replay_flash": "Eng nawn leh rawh",
    "cancel": "Cancel",
    "exit": "Tawp rawh",
    "object_to_find": "Thil zawn tur:",
    "correct_match": "I thlang dik e!",
    "wrong_match": "Chhin nawn leh rawh!",
    "find_different": "A danglam ber thlang rawh",
    "read_story": "Thawnthu ngaithla rawh",
    "keep_going": "Hmet chhunzawm rawh",
    "wrong_seq": "I hmet sual e! En nawn leh rawh.",
    "next_item_hint": "Hint: A dawt leh tur chu",
    "go_to_questions": "Zawhna ah kal rawh",
    "question": "Zawhna",
    "submit_answer": "Submit leh rawh",
    "shuffle": "Thlang nawn leh",
    "generating": "Aw siam mek...",
    "playing": "Rawn ri mek... Tawp rawh",
    "error": "Fiah lo"
  },
  "Khasi": {
    "play": "Leh",
    "start": "Sdang",
    "next": "Ka Ban Bud",
    "submit": "Phah",
    "try_again": "Pyrshang Pat",
    "back": "Kynran",
    "play_again": "Leh Pat",
    "listen": "Sngap",
    "repeat": "Pule Pat",
    "return_dashboard": "Leit Sha Ka Dashboard",
    "time_left": "Ka Por Kaba Sah",
    "score": "Ka Point",
    "hints": "Ki Hint Pyndonkam",
    "level": "Kyrdan",
    "support_active": "Jingkyrshan (Kaba Suk)",
    "watch_carefully": "Peit bha ïa ka jingfleiñ ki dur!",
    "repeat_pattern": "Bud pat ïa ka jingfleiñ...",
    "great_job": "Kaba khraw bha!",
    "game_over": "Kaba Kut",
    "clicks": "Tup",
    "progress": "Jingnangroi",
    "replay_flash": "Pynshai biang",
    "cancel": "Cancel",
    "exit": "Mih",
    "object_to_find": "Wad ïa ka tiar:",
    "correct_match": "Kaba dei!",
    "wrong_match": "Pyrshang pat!",
    "find_different": "Jied ïa kaba pher",
    "read_story": "Pule Khana",
    "keep_going": "Bteng ban leh",
    "wrong_seq": "Bakla ka jingïabud. Peit biang.",
    "next_item_hint": "Hint: Ka tiar kaba bud ka dei",
    "go_to_questions": "Leit sha ki jingkylli",
    "question": "Jingkylli",
    "submit_answer": "Phah ïa ka jubab",
    "shuffle": "Pynkynriah",
    "generating": "Pynmih Sur...",
    "playing": "Kaba Put... Pynsangeh",
    "error": "Jinggual"
  },
  "Garo": {
    "play": "Kalai",
    "start": "A·bachengbo",
    "next": "Re·anggal",
    "submit": "On·gitchipe",
    "try_again": "Altah ta·rak",
    "back": "Re·pil",
    "play_again": "Kaltah kalai",
    "listen": "Knange",
    "repeat": "Minggitchipe",
    "return_dashboard": "Dashboard-ona re·pil",
    "time_left": "Somay dongku",
    "score": "Point",
    "hints": "Hint dakman",
    "level": "Gadang",
    "support_active": "Dakchakani (Nengramgipa)",
    "watch_carefully": "Mese·ani chinrangko neng·ramgo niobo!",
    "repeat_pattern": "Mesogipa gita dakaibo...",
    "great_job": "Namgipa kam!",
    "game_over": "Kal·ani matchotgimin",
    "clicks": "Nang·atgipa",
    "progress": "A·chong",
    "replay_flash": "Mese·pil·bo",
    "cancel": "Cancel",
    "exit": "Re·ongbo",
    "object_to_find": "Bostuko niobo:",
    "correct_match": "Tik daka!",
    "wrong_match": "Kaltaibo!",
    "find_different": "Dingtanggipako bisarobo",
    "read_story": "Golipko knange",
    "keep_going": "Dakaibo",
    "wrong_seq": "Gual daka. Nio pil·bo.",
    "next_item_hint": "Hint: Re·anggipa bostude",
    "go_to_questions": "Chongmot sing·anirangna re·bo",
    "question": "Sing·ani",
    "submit_answer": "Sing·aniko on·bo",
    "shuffle": "Dingtangataibo",
    "generating": "Soli tarak...",
    "playing": "Kalku... Re·pil",
    "error": "Gualani"
  },
  "Nepali": {
    "play": "खेल्नुहोस्",
    "start": "सुरु गर्नुहोस्",
    "next": "अर्को",
    "submit": "बुझाउनुहोस्",
    "try_again": "फेरि प्रयास गर्नुहोस्",
    "back": "पछाडि",
    "play_again": "फेरि खेल्नुहोस्",
    "listen": "सुन्नुहोस्",
    "repeat": "दोहोर्याउनुहोस्",
    "return_dashboard": "ड्यासबोर्डमा फर्कनुहोस्",
    "time_left": "बाँकी समय",
    "score": "अंक",
    "hints": "प्रयोग गरिएको संकेत",
    "level": "स्तर",
    "support_active": "सहायता सक्रिय (सजिलो संस्करण)",
    "watch_carefully": "तस्बिरहरूको क्रम ध्यान दिएर हेर्नुहोस्!",
    "repeat_pattern": "देखाएको क्रम दोहोर्याउनुहोस्...",
    "great_job": "धेरै राम्रो!",
    "game_over": "खेल समाप्त",
    "clicks": "क्लिकहरू",
    "progress": "प्रगति",
    "replay_flash": "क्रम फेरि देखाउनुहोस्",
    "cancel": "रद्द गर्नुहोस्",
    "exit": "बाहिरिनुहोस्",
    "object_to_find": "वस्तु पत्ता लगाउनुहोस्:",
    "correct_match": "सही मिलान!",
    "wrong_match": "फेरि प्रयास गर्नुहोस्!",
    "find_different": "फरक वस्तु पत्ता लगाउनुहोस्",
    "read_story": "कथा सुन्नुहोस्",
    "keep_going": "गर्दै जानुहोस्",
    "wrong_seq": "गलत क्रम। फेरि हेर्नुहोस्।",
    "next_item_hint": "संकेत: अर्को तस्बिर",
    "go_to_questions": "प्रश्नहरूमा जानुहोस्",
    "question": "प्रश्न",
    "submit_answer": "उत्तर बुझाउनुहोस्",
    "shuffle": "फेरबदल गर्नुहोस्",
    "generating": "आवाज तयार हुँदैछ...",
    "playing": "बज्दैछ... रोक्नुहोस्",
    "error": "त्रुटि"
  },
  "Hindi": {
    "play": "खेलें",
    "start": "शुरू करें",
    "next": "अगला",
    "submit": "जमा करें",
    "try_again": "फिर कोशिश करें",
    "back": "पीछे",
    "play_again": "फिर खेलें",
    "listen": "सुनें",
    "repeat": "दोहराएं",
    "return_dashboard": "डैशबोर्ड पर लौटें",
    "time_left": "समय शेष",
    "score": "अंक",
    "hints": "इस्तेमाल किए गए संकेत",
    "level": "स्तर",
    "support_active": "सहायता सक्रिय (आसान संस्करण)",
    "watch_carefully": "चमकते हुए क्रम को ध्यान से देखें!",
    "repeat_pattern": "दिखाए गए पैटर्न को दोहराएं...",
    "great_job": "बहुत बढ़िया!",
    "game_over": "खेल समाप्त",
    "clicks": "क्लिक",
    "progress": "प्रगति",
    "replay_flash": "क्रम फिर से दिखाएं",
    "cancel": "रद्द करें",
    "exit": "बाहर निकलें",
    "object_to_find": "वस्तु खोजें:",
    "correct_match": "सही मिलान!",
    "wrong_match": "फिर कोशिश करें!",
    "find_different": "अलग वस्तु खोजें",
    "read_story": "कहानी पढ़ें",
    "keep_going": "जारी रखें",
    "wrong_seq": "ओह! गलत क्रम। फिर से देखें।",
    "next_item_hint": "संकेत: अगला चित्र है",
    "go_to_questions": "प्रश्नों पर जाएं",
    "question": "प्रश्न",
    "submit_answer": "उत्तर जमा करें",
    "shuffle": "फेरबदल करें",
    "generating": "आवाज तैयार की जा रही है...",
    "playing": "बज रहा है... बंद करने के लिए क्लिक करें",
    "error": "त्रुटि"
  }
};

// Return translation with English fallback
export function getTranslation(language, key) {
  const langData = SHARED_LOCALIZATIONS[language] || SHARED_LOCALIZATIONS["English"];
  const val = langData[key] || SHARED_LOCALIZATIONS["English"][key];
  if (val) return val;

  const dictionary = {
    "select_activity": {
      "English": "Select a Cognitive Activity",
      "Assamese": "এটা জ্ঞানীয় কাৰ্য বাছক",
      "Bengali": "একটি জ্ঞানীয় কাজ নির্বাচন করুন",
      "Meitei": "ꯀꯣꯒ꯭ꯅꯤꯇꯤꯕ ꯊꯕꯛ ꯑꯃꯥ ꯈꯟꯕꯤꯌꯨ",
      "Mizo": "Rilru sawizawina thlang rawh",
      "Khasi": "Jied ïa ka kam kynmaw",
      "Garo": "Kal·ani chongmot bisarobo",
      "Nepali": "एक संज्ञानात्मक गतिविधि छान्नुहोस्",
      "Hindi": "संज्ञानात्मक गतिविधि चुनें"
    },
    "age": {
      "English": "Age",
      "Assamese": "বয়স",
      "Bengali": "বয়স",
      "Meitei": "ꯆꯍꯤ",
      "Mizo": "Kum",
      "Khasi": "Ka rta",
      "Garo": "Bilsi",
      "Nepali": "उमेर",
      "Hindi": "आयु"
    },
    "gender": {
      "English": "Gender",
      "Assamese": "লিংগ",
      "Bengali": "লিঙ্গ",
      "Meitei": "ꯅꯨꯄꯥ/ꯅꯨꯄꯤ",
      "Mizo": "Mipa/Hmeichhia",
      "Khasi": "Kynthei/Shynrang",
      "Garo": "Me·asa/Me·chik",
      "Nepali": "लिङ्ग",
      "Hindi": "लिंग"
    },
    "state": {
      "English": "State",
      "Assamese": "ৰাজ্য",
      "Bengali": "রাজ্য",
      "Meitei": "ꯁ꯭ꯇꯦꯠ",
      "Mizo": "State",
      "Khasi": "Ka Jylla",
      "Garo": "State",
      "Nepali": "राज्य",
      "Hindi": "राज्य"
    },
    "language": {
      "English": "Language",
      "Assamese": "ভাষা",
      "Bengali": "ভাষা",
      "Meitei": "ꯂꯣꯟ",
      "Mizo": "Tawng",
      "Khasi": "Ka Ktien",
      "Garo": "Ku·sik",
      "Nepali": "भाषा",
      "Hindi": "भाषा"
    },
    "todays_activity": {
      "English": "Today's Cognitive Activity",
      "Assamese": "আজিৰ জ্ঞানীয় কাৰ্যকলাপ",
      "Bengali": "আজকের জ্ঞানীয় কাজ",
      "Meitei": "ꯉꯁꯤꯒꯤ ꯀꯣꯒ꯭ꯅꯤꯇꯤꯕ ꯊꯕꛛ",
      "Mizo": "Vawiin rilru sawizawina",
      "Khasi": "Ka kam kynmaw ban leh mynta",
      "Garo": "Da·salni chongmot kal·ani",
      "Nepali": "आजको संज्ञानात्मक गतिविधि",
      "Hindi": "आज की गतिविधि"
    },
    "recommended_for_you": {
      "English": "Recommended for you",
      "Assamese": "আপোনাৰ বাবে পৰামৰ্শ দিয়া হৈছে",
      "Bengali": "আপনার জন্য প্রস্তাবিত",
      "Meitei": "ꯅꯍꯥꛛꯀꯤꯗꯃꛛ ꯔꯦꯀꯣꯃꯦꯟꯗ ꯇꯧꯔꯕꪥ",
      "Mizo": "I tana tha ber tura thlan",
      "Khasi": "Kaba la ai buh kyrpang ïa phi",
      "Garo": "Nang·na chongmot bil·ani",
      "Nepali": "तपाईंको लागि सिफारिस गरिएको",
      "Hindi": "आपके लिए अनुशंसित"
    },
    "why_this_activity": {
      "English": "Why this activity?",
      "Assamese": "এই খেলটো কিয় বাছনি কৰা হ’ল?",
      "Bengali": "এই কাজটি কেন?",
      "Meitei": "ꯊꯕꛛ ꯑꯁꯤ ꯀꯔꯤꯒꯤꯅꯣ?",
      "Mizo": "Engvanga he thlang nge i nih?",
      "Khasi": "Balei jied ïa ka kam?",
      "Garo": "Mina ia kal·aniko kal·na nanga?",
      "Nepali": "किन यो गतिविधि?",
      "Hindi": "यह गतिविधि क्यों?"
    },
    "play_recommended": {
      "English": "Start Recommended Game",
      "Assamese": "পৰামৰ্শ দিয়া খেলটো খেলক",
      "Bengali": "প্রস্তাবিত খেলাটি শুরু করুন",
      "Meitei": "ꯔꯦꯀꯣꯃꯦꯟꯗ ꯇꯧꯔꯕꪥ ꯒꯦꯝ ꯍꯧꯕꯤꯌꯨ",
      "Mizo": "Khel tur thlan hi tan rawh",
      "Khasi": "Sdang ïa ka game ba la ai buh",
      "Garo": "Chongmot kal·aniko a·bachengbo",
      "Nepali": "सिफारिस गरिएको खेल सुरु गर्नुहोस्",
      "Hindi": "अनुशंसित खेल शुरू करें"
    }
  };

  if (dictionary[key]) {
    return dictionary[key][language] || dictionary[key]["English"] || key;
  }

  return key;
}

export const REGIONAL_ASSETS = {
  "Assam": [
    { id: "jaapi", emoji: "👒", name: { "English": "Jaapi Hat", "Assamese": "জাপি", "Bengali": "জাপি টুপি", "Hindi": "असम की जापी" } },
    { id: "tea", emoji: "🍵", name: { "English": "Assam Tea", "Assamese": "চাহ", "Bengali": "চা", "Hindi": "असम की चाय" } },
    { id: "rhino", emoji: "🦏", name: { "English": "One-horned Rhino", "Assamese": "গড়", "Bengali": "গণ্ডার", "Hindi": "एक सींग वाला गैंडा" } },
    { id: "bamboo", emoji: "🎋", name: { "English": "Bamboo", "Assamese": "বাঁহ", "Bengali": "বাঁশ", "Hindi": "बांस" } },
    { id: "river", emoji: "🚣", name: { "English": "Rowboat", "Assamese": "নাও", "Bengali": "নৌকা", "Hindi": "नाव" } },
    { id: "rice", emoji: "🍚", name: { "English": "Rice Bowl", "Assamese": "ভাতৰ বাতি", "Bengali": "ভাতের থালা", "Hindi": "चावल" } },
    { id: "hornbill", emoji: "🐦", name: { "English": "Hornbill", "Assamese": "ধনেশ পক্ষী", "Bengali": "ধনেশ পাখি", "Hindi": "धनेश पक्षी" } }
  ],
  "Meghalaya": [
    { id: "bamboo", emoji: "🎋", name: { "English": "Bamboo", "Khasi": "Kdait", "Garo": "Wa·a", "Hindi": "बांस" } },
    { id: "cloud", emoji: "☁️", name: { "English": "Cloud", "Khasi": "Lyoh", "Garo": "A·chiga", "Hindi": "बादल" } },
    { id: "waterfall", emoji: "🌊", name: { "English": "Waterfall", "Khasi": "Kshaid", "Garo": "Chisik", "Hindi": "झरना" } },
    { id: "orange", emoji: "🍊", name: { "English": "Khasi Mandarin", "Khasi": "Sohniamtra", "Garo": "Te·gatchi", "Hindi": "संतरा" } },
    { id: "basket", emoji: "🧺", name: { "English": "Traditional Basket", "Khasi": "Kriah", "Garo": "Kok", "Hindi": "पारंपरिक टोकरी" } },
    { id: "drum", emoji: "🥁", name: { "English": "Garo Wangala Drum", "Khasi": "Sing", "Garo": "Dama", "Hindi": "गारो नगाड़ा" } },
    { id: "hill", emoji: "⛰️", name: { "English": "Khasi Hill", "Khasi": "Lum", "Garo": "A·bri", "Hindi": "खासी पहाड़ी" } }
  ],
  "Manipur": [
    { id: "lily", emoji: "🌸", name: { "English": "Shirui Lily", "Meitei": "শিৰুই লিলি", "Hindi": "शिरुई लिली" } },
    { id: "deer", emoji: "🦌", name: { "English": "Sangai Deer", "Meitei": "সাংগাই", "Hindi": "संगाई हिरण" } },
    { id: "lake", emoji: "🚣", name: { "English": "Loktak Lake Boat", "Meitei": "হী", "Hindi": "लोकतक झील की नाव" } },
    { id: "drum", emoji: "🥁", name: { "English": "Pung Drum", "Meitei": "পুং", "Hindi": "पुंग ढोल" } },
    { id: "bamboo", emoji: "🎋", name: { "English": "Bamboo shoot", "Meitei": "সোইবুম", "Hindi": "बांस की कोपलें" } },
    { id: "shawl", emoji: "🧣", name: { "English": "Manipuri Shawl", "Meitei": "ফী", "Hindi": "मणिपुरी शॉल" } },
    { id: "fish", emoji: "🐟", name: { "English": "Familiar Fish", "Meitei": "ঙা", "Hindi": "मछली" } }
  ],
  "Mizoram": [
    { id: "bamboo", emoji: "🎋", name: { "English": "Bamboo", "Mizo": "Mau", "Hindi": "बांस" } },
    { id: "gong", emoji: "🔔", name: { "English": "Mizo Gong", "Mizo": "Darbu", "Hindi": "मिज़ो घंटा" } },
    { id: "shawl", emoji: "🧣", name: { "English": "Puan Shawl", "Mizo": "Puan", "Hindi": "पुआन शॉल" } },
    { id: "drum", emoji: "🥁", name: { "English": "Mizo Drum", "Mizo": "Khuang", "Hindi": "मिज़ो ढोल" } },
    { id: "anthill", emoji: "🐜", name: { "English": "Local Ant", "Mizo": "Fanghmir", "Hindi": "चींटी" } },
    { id: "flower", emoji: "🌸", name: { "English": "Red Vanda", "Mizo": "Senhri", "Hindi": "लाल वंडा फूल" } },
    { id: "bird", emoji: "🐦", name: { "English": "Mrs. Hume's Pheasant", "Mizo": "Vavu", "Hindi": "तीतर पक्षी" } }
  ],
  "Sikkim": [
    { id: "panda", emoji: "🐼", name: { "English": "Red Panda", "Nepali": "रातो पाण्डा" } },
    { id: "rhododendron", emoji: "🌺", name: { "English": "Rhododendron", "Nepali": "लालीगुराँस" } },
    { id: "mountain", emoji: "🏔️", name: { "English": "Kanchenjunga", "Nepali": "कञ्चनजङ्घा" } },
    { id: "cardamom", emoji: "🌱", name: { "English": "Black Cardamom", "Nepali": "अलैंची" } },
    { id: "tea", emoji: "🍵", name: { "English": "Temi Tea", "Nepali": "चिया" } },
    { id: "bell", emoji: "🔔", name: { "English": "Monastery Bell", "Nepali": "घण्टी" } },
    { id: "flag", emoji: "🚩", name: { "English": "Prayer Flag", "Nepali": "ध्वजा" } }
  ],
  "Tripura": [
    { id: "pineapple", emoji: "🍍", name: { "English": "Queen Pineapple", "Bengali": "আনারস" } },
    { id: "bamboo", emoji: "🎋", name: { "English": "Bamboo Crafts", "Bengali": "বাঁশ" } },
    { id: "orange", emoji: "🍊", name: { "English": "Jampui Orange", "Bengali": "কমলালেবু" } },
    { id: "temple", emoji: "🛕", name: { "English": "Tripureswari Temple", "Bengali": "মন্দির" } },
    { id: "fish", emoji: "🐟", name: { "English": "Local Fish", "Bengali": "মাছ" } },
    { id: "cotton", emoji: "🧶", name: { "English": "Handloom Cotton", "Bengali": "সুতো" } },
    { id: "rice", emoji: "🌾", name: { "English": "Paddy fields", "Bengali": "ধান" } }
  ],
  "Default": [
    { id: "apple", emoji: "🍎", name: { "English": "Apple" } },
    { id: "banana", emoji: "🍌", name: { "English": "Banana" } },
    { id: "cat", emoji: "🐱", name: { "English": "Cat" } },
    { id: "dog", emoji: "🐶", name: { "English": "Dog" } },
    { id: "car", emoji: "🚗", name: { "English": "Car" } },
    { id: "house", emoji: "🏠", name: { "English": "House" } },
    { id: "ball", emoji: "⚽", name: { "English": "Ball" } }
  ]
};

export function getRegionalAssets(state, lang) {
  const assets = REGIONAL_ASSETS[state] || REGIONAL_ASSETS["Default"];
  return assets.map(item => ({
    id: item.id,
    emoji: item.emoji,
    name: item.name[lang] || item.name["English"] || item.id
  }));
}

const FAMILY_TRANSLATIONS = {
  "English": {
    "mother": "Mother",
    "father": "Father",
    "daughter": "Daughter",
    "son": "Son",
    "brother": "Brother",
    "sister": "Sister",
    "grandchild": "Grandchild",
    "spouse": "Spouse",
    "caregiver": "Caregiver",
    "other": "Other",
    "who_is_this_person": "Who is this person?",
    "what_is_relationship": "What is this person's relationship to you?",
    "correct_family_feedback": "Well done! This is your {relation}.",
    "incorrect_family_feedback": "That's okay. This is your {relation}. Let's try the next one.",
    "family_member_recognition": "Family Member Recognition"
  },
  "Assamese": {
    "mother": "মা",
    "father": "দেউতা",
    "daughter": "জীয়াৰী",
    "son": "পুত্ৰ",
    "brother": "ভাই",
    "sister": "ভনী",
    "grandchild": "নাতি/নাতিনী",
    "spouse": "পত্নী/গিৰীয়েক",
    "caregiver": "যত্নলোৱা ব্যক্তি",
    "other": "অন্যান্য",
    "who_is_this_person": "এইজন কোন হয়?",
    "what_is_relationship": "আপোনাৰ লগত তেওঁৰ সম্পৰ্ক কি?",
    "correct_family_feedback": "বঢ়িয়া! এইয়া আপোনাৰ {relation}।",
    "incorrect_family_feedback": "একো কথা নাই। এইয়া আপোনাৰ {relation} হয়। আৰম্ভ কৰক পৰৱৰ্তী চেষ্টা।",
    "family_member_recognition": "পৰিয়ালৰ সদস্য চিনাক্তকৰণ"
  },
  "Bengali": {
    "mother": "মা",
    "father": "বাবা",
    "daughter": "মেয়ে",
    "son": "ছেলে",
    "brother": "ভাই",
    "sister": "বোন",
    "grandchild": "নাতি/নাতনি",
    "spouse": "স্বামী/স্ত্রী",
    "caregiver": "সেবাদानকারী",
    "other": "অন্যান্য",
    "who_is_this_person": "ইনি কে হন?",
    "what_is_relationship": "আপনার সাথে এনার সম্পর্ক কি?",
    "correct_family_feedback": "খুব ভালো! ইনি আপনার {relation}।",
    "incorrect_family_feedback": "ঠিক আছে। ইনি আপনার {relation}। চলুন পরেরটি চেষ্টা করি।",
    "family_member_recognition": "পরিবারের সদস্য সনাক্তকরণ"
  },
  "Meitei": {
    "mother": "ইমা",
    "father": "ইপা",
    "daughter": "ইচা নুপী",
    "son": "ইচা নুপা",
    "brother": "ইনাও নুপা",
    "sister": "ইচল নুপী",
    "grandchild": "সু",
    "spouse": "লোইনবী/মপুৰোয়বা",
    "caregiver": "চেকশিনবী",
    "other": "অতোপ্পা",
    "who_is_this_person": "মী অসি কনানো?",
    "what_is_relationship": "মী অসিগা ইগা কনৌ থৈনৈ?",
    "correct_family_feedback": "য়াম্না ফৈ! অসি নহাক্কী {relation} নি।",
    "incorrect_family_feedback": "য়েংগে, অসি নহাক্কী {relation} নি। মথঙগী অমা হোৎনবা।",
    "family_member_recognition": "ইমুং মনুং খঙদোকপা"
  },
  "Khasi": {
    "mother": "Mei",
    "father": "Pa",
    "daughter": "Khadduh",
    "son": "Khun",
    "brother": "Bah",
    "sister": "Kong",
    "grandchild": "Ksiew",
    "spouse": "Lok",
    "caregiver": "Nongsumar",
    "other": "Kiwei",
    "who_is_this_person": "Uei une/uno?",
    "what_is_relationship": "Kiei kane bad phi?",
    "correct_family_feedback": "Bha bha! Une dei u/ka {relation} jong phi.",
    "incorrect_family_feedback": "La biang. Une dei u/ka {relation} jong phi. Ia pyrshang pat ia kawei.",
    "family_member_recognition": "Ithuh Iaki Dkhot Longiing"
  },
  "Mizo": {
    "mother": "Nu",
    "father": "Pa",
    "daughter": "Fanu",
    "son": "Fapa",
    "brother": "Unaupa",
    "sister": "Unaunu",
    "grandchild": "Tu",
    "spouse": "Kawppui",
    "caregiver": "Enkawltu",
    "other": "Dang",
    "who_is_this_person": "Tunge he mi hi?",
    "what_is_relationship": "In inlaichinna engnge ni?",
    "correct_family_feedback": "Tha lutuk! Hei hi i {relation} a ni e.",
    "incorrect_family_feedback": "A pawi lo. Hei hi i {relation} a ni e. A dawt leh le.",
    "family_member_recognition": "Chhungte Hriatfiahna"
  },
  "Hindi": {
    "mother": "माता",
    "father": "पिता",
    "daughter": "बेटी",
    "son": "बेटा",
    "brother": "भाई",
    "sister": "बहन",
    "grandchild": "पोता/पोती",
    "spouse": "जीवनसाथी",
    "caregiver": "देखभालकर्ता",
    "other": "अन्य",
    "who_is_this_person": "यह व्यक्ति कौन है?",
    "what_is_relationship": "इस व्यक्ति का आपसे क्या संबंध है?",
    "correct_family_feedback": "बहुत अच्छे! यह आपकी/का {relation} है।",
    "incorrect_family_feedback": "कोई बात नहीं। यह आपकी/का {relation} है। चलिए अगला प्रयास करते हैं।",
    "family_member_recognition": "पारिवारिक सदस्य पहचान"
  }
};

const DASHBOARD_TRANSLATIONS = {
  "English": {
    "todays_progress": "Today's Progress",
    "todays_story": "Today's Cultural Story",
    "read_story": "Read Story",
    "todays_reminders": "Today's Reminders",
    "your_progress": "Your Progress",
    "games_completed": "Games Completed",
    "current_level": "Current Level",
    "recent_performance": "Recent Performance",
    "edit_profile": "Edit Profile",
    "view_profile": "View Profile",
    "start_game": "Start Game",
    "no_reminders": "No reminders scheduled for today. Enjoy your day! ☀️",
    "no_games_yet": "No cognitive games played yet. Start your first activity!",
    "good_morning": "Good Morning",
    "good_afternoon": "Good Afternoon",
    "good_evening": "Good Evening",
    "welcome": "Welcome",
    "patient_profile": "Patient Profile",
    "daily_goal": "Daily Goal",
    "activities": "Activities",
    "stories": "Stories",
    "reminders": "Reminders"
  },
  "Assamese": {
    "todays_progress": "আজিৰ অগ্ৰগতি",
    "todays_story": "আজিৰ সাংস্কৃতিক সাধু",
    "read_story": "সাধুটো পঢ়ক",
    "todays_reminders": "আজিৰ সোঁৱৰণী",
    "your_progress": "আপোনাৰ অগ্ৰগতি",
    "games_completed": "সমাপ্ত খেলসমূহ",
    "current_level": "বৰ্তমান স্তৰ",
    "recent_performance": "শেহতীয়া প্ৰদৰ্শন",
    "edit_profile": "প্ৰফাইল সম্পাদনা",
    "view_profile": "প্ৰফাইল চাওক",
    "start_game": "খেল আৰম্ভ কৰক",
    "no_reminders": "আজিৰ বাবে কোনো সোঁৱৰণী নাই। আপোনাৰ দিনটো শুভ হওক! ☀️",
    "no_games_yet": "এতিয়ালৈকে কোনো খেল খেলা হোৱা নাই। আপোনাৰ প্ৰথম কাৰ্য আৰম্ভ কৰক!",
    "good_morning": "শুভ প্ৰভাত",
    "good_afternoon": "শুভ অপৰাহ্ণ",
    "good_evening": "শুভ সন্ধিয়া",
    "welcome": "স্বাগতম",
    "patient_profile": "ৰোগীৰ প্ৰফাইল",
    "daily_goal": "দৈনিক লক্ষ্য",
    "activities": "কাৰ্য্যকলাপ",
    "stories": "সাধুসমূহ",
    "reminders": "সোঁৱৰণীসমূহ"
  },
  "Bengali": {
    "todays_progress": "আজকের অগ্রগতি",
    "todays_story": "আজকের সাংস্কৃতিক গল্প",
    "read_story": "গল্পটি পড়ুন",
    "todays_reminders": "আজকের অনুস্মারক",
    "your_progress": "আপনার অগ্রগতি",
    "games_completed": "সম্পন্ন খেলা",
    "current_level": "বর্তমান স্তর",
    "recent_performance": "সাম্প্রতিক ফলাফল",
    "edit_profile": "প্রোফাইল সম্পাদনা",
    "view_profile": "প্রোফাইল দেখুন",
    "start_game": "খেলা শুরু করুন",
    "no_reminders": "আজকের জন্য কোনো অনুস্মারক নেই। আপনার দিনটি শুভ হোক! ☀️",
    "no_games_yet": "এখনো কোনো খেলা খেলা হয়নি। আপনার প্রথম কাজ শুরু করুন!",
    "good_morning": "সুপ্রভাত",
    "good_afternoon": "শুভ অপরাহ্ন",
    "good_evening": "শুভ সন্ধ্যা",
    "welcome": "স্বাগতম",
    "patient_profile": "রোগীর প্রোফাইল",
    "daily_goal": "দৈনিক লক্ষ্য",
    "activities": "কার্যকলাপ",
    "stories": "গল্প",
    "reminders": "অনুস্মারক"
  },
  "Meitei": {
    "todays_progress": "ꯉꯁꯤꯒꯤ ꯃꯥꯡꯖꯤꯜ",
    "todays_story": "ꯉꯁꯤꯒꯤ ꯀꯂꯆꯔꯦꯜ ꯋꯥꯔꯤ",
    "read_story": "ꯋꯥꯔꯤ ꯄꯥꯕꯤꯌꯨ",
    "todays_reminders": "ꯉꯁꯤꯒꯤ ꯅꯤꯡꯁꯤꯡꯍꯧꯕibi",
    "your_progress": "ꯅꯍꯥꯛꯀꯤ ꯃꯥꯡꯖꯤꯜ",
    "games_completed": "ꯂꯣꯏꯔꯕꯥ ꯁꯥꯟꯅꯕꯁꯤꯡ",
    "current_level": "ꯍꯧꯖꯤꯛ ꯂꯩꯔꯤꯕꯥ ꯊꯥꯛ",
    "recent_performance": "ꯍꯟꯗꯛꯀꯤ ꯊꯕꯛ",
    "edit_profile": "ꯄ꯭ꯔꯣꯐꯥꯏꯜ ꯁꯦꯝꯗꯣꯛꯎ",
    "view_profile": "ꯄ꯭ꯔꯣꯐꯥꯏꯜ ꯌꯦꯡꯕꯤꯌꯨ",
    "start_game": "ꯁꯥꯟꯅꯕꯥ ꯍꯧꯕꯤꯌꯨ",
    "no_reminders": "ꯉꯁꯤꯒꯤ ꯅꯤꯡꯁꯤꯡꯍꯧꯕibi ꯂꯩꯇꯦ। ꯅꯨꯡꯉꯥꯏꯅꯥ ꯂꯩꯕꯤꯌꯨ! ☀️",
    "no_games_yet": "ꯁꯥꯟꯅꯕꯥ ꯍꯧꯗ꯭ꯔꯤ। ꯑꯍꯥꯅꯕꯥ ꯊꯕꯛ ꯍꯧꯕꯤꯌꯨ!",
    "good_morning": "ꯅꯨꯡꯁꯤꯔꯕꯥ ꯑꯌꯨꯛ",
    "good_afternoon": "ꯅꯨꯡꯁꯤꯔꯕꯥ ꯅꯨꯡꯊꯤꯜ",
    "good_evening": "ꯅꯨꯡꯁꯤꯔꯕꯥ ꯅꯨꯃꯤꯗꯥꯡ",
    "welcome": "ꯇꯔꯥꯝꯅꯥ ꯑꯣꯛꯆꯔꯤ",
    "patient_profile": "ꯄꯦꯁꯦꯟꯠ ꯄ꯭ꯔꯣꯐꯥꯏꯜ",
    "daily_goal": "ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯄꯥꯟꯗꯝ",
    "activities": "ꯊꯕꯛꯁꯤꯡ",
    "stories": "ꯋꯥꯔꯤꯁꯤꯡ",
    "reminders": "ꯅꯤꯡꯁꯤꯡꯍꯧꯕꯁꯤꯡ"
  },
  "Khasi": {
    "todays_progress": "Ka Jingroi Mynta",
    "todays_story": "Ka Puriskam Tynrai Mynta",
    "read_story": "Pule ia ka Puriskam",
    "todays_reminders": "Ki Jingkynmaw Mynta",
    "your_progress": "Ka Jingroi Jong Me",
    "games_completed": "Ki Jingiakhun ba la dep",
    "current_level": "Ka kyrdan mynta",
    "recent_performance": "Ka rukom leh mynta",
    "edit_profile": "Pynbha ia ka Profile",
    "view_profile": "Peit ia ka Profile",
    "start_game": "Sdang Jingiakhun",
    "no_reminders": "Ym don jingkynmaw mynta ka sngi. Khublei shisngi! ☀️",
    "no_games_yet": "Ym pat don jingiakhun ba la dep. Sdang mynta!",
    "good_morning": "Khublei Step",
    "good_afternoon": "Khublei Sngi",
    "good_evening": "Khublei Janmiet",
    "welcome": "Pdiang burom",
    "patient_profile": "Ka Profile u Nongpang",
    "daily_goal": "Ka thong shisngi",
    "activities": "Ki Kam",
    "stories": "Ki Puriskam",
    "reminders": "Ki Jingkynmaw"
  },
  "Mizo": {
    "todays_progress": "Vawiin hmasawnna",
    "todays_story": "Vawiin thawnthu ngaihnawm",
    "read_story": "Thawnthu chhiar rawh",
    "todays_reminders": "Vawiin hriatnawnna",
    "your_progress": "I hmasawnna",
    "games_completed": "Infiamna zawh tawhte",
    "current_level": "Tun dinhmun Level",
    "recent_performance": "Tunhnaia chetvel dan",
    "edit_profile": "Profile siamthatna",
    "view_profile": "Profile enna",
    "start_game": "Infiamna tan rawh",
    "no_reminders": "Vawiin atan hriatnawnna a awm rih lo. Ni nuam tak hmang rawh! ☀️",
    "no_games_yet": "Infiamna khelh a la awm lo. A hmasa ber hi tan rawh!",
    "good_morning": "Chibai zing chibai",
    "good_afternoon": "Chibai chhun chibai",
    "good_evening": "Chibai tlai chibai",
    "welcome": "Chibai",
    "patient_profile": "Damin Profile",
    "daily_goal": "Ni tin tum",
    "activities": "Thiltihte",
    "stories": "Thawnthute",
    "reminders": "Hriatnawnnate"
  },
  "Hindi": {
    "todays_progress": "आज की प्रगति",
    "todays_story": "आज की सांस्कृतिक कहानी",
    "read_story": "कहानी पढ़ें",
    "todays_reminders": "आज के रिमाइन्डर",
    "your_progress": "आपकी प्रगति",
    "games_completed": "पूरे किए गए खेल",
    "current_level": "वर्तमान स्तर",
    "recent_performance": "हाल का प्रदर्शन",
    "edit_profile": "प्रोफ़ाइल संपादित करें",
    "view_profile": "प्रोफ़ाइल देखें",
    "start_game": "खेल शुरू करें",
    "no_reminders": "आज के लिए कोई रिमाइन्डर नहीं है। आपका दिन शुभ हो! ☀️",
    "no_games_yet": "अभी तक कोई खेल नहीं खेला गया है। अपनी पहली गतिविधि शुरू करें!",
    "good_morning": "शुभ प्रभात",
    "good_afternoon": "शुभ दोपहर",
    "good_evening": "शुभ संध्या",
    "welcome": "स्वागत है",
    "patient_profile": "मरीज की प्रोफ़ाइल",
    "daily_goal": "दैनिक लक्ष्य",
    "activities": "गतिविधियां",
    "stories": "कहानियां",
    "reminders": "रिमाइन्डर"
  }
};

Object.keys(FAMILY_TRANSLATIONS).forEach(lang => {
  if (SHARED_LOCALIZATIONS[lang]) {
    Object.assign(SHARED_LOCALIZATIONS[lang], FAMILY_TRANSLATIONS[lang]);
  }
});

Object.keys(DASHBOARD_TRANSLATIONS).forEach(lang => {
  if (SHARED_LOCALIZATIONS[lang]) {
    Object.assign(SHARED_LOCALIZATIONS[lang], DASHBOARD_TRANSLATIONS[lang]);
  }
});
